// Re-export from mdx for backwards compatibility
export {
  getAllPosts,
  getPostBySlug,
  getRecentPosts,
  getPostsByCategory,
  getPostsByTag,
  getAllCategories,
  getAllTags,
  getTagsByCategory,
  getCategoriesWithTags,
  getRootCategoriesWithTags,
  buildCategoryTree,
  getCategoryBySlugPath,
  getAllCategoriesHierarchical,
  getPostsByCategoryPath,
  getChildCategories,
  getChildCategoriesWithTags,
  getRootCategories,
  getRelatedPosts,
  getAdjacentPosts,
} from './mdx';
