// Re-export from mdx for backwards compatibility
export {
  getAllPosts,
  getPublicPosts,
  getPostBySlug,
  getRecentPosts,
  getPostsByCategory,
  getPostsByTag,
  getAllCategories,
  getAllTags,
  getTagsByCategory,
  getCategoriesWithTags,
  getRootCategoriesWithTags,
  buildCategoryTree,
  getCategoryBySlugPath,
  getAllCategoriesHierarchical,
  getPostsByCategoryPath,
  getChildCategories,
  getChildCategoriesWithTags,
  getRootCategories,
  getRelatedPosts,
  getAdjacentPosts,
  // Async versions (read from GitHub when available)
  getAllPostsAsync,
  getPostBySlugAsync,
  getRecentPostsAsync,
  getAllCategoriesAsync,
  getAllTagsAsync,
  getRootCategoriesAsync,
  getRootCategoriesWithTagsAsync,
  getRelatedPostsAsync,
  getAdjacentPostsAsync,
  getCategoryBySlugPathAsync,
  getAllCategoriesHierarchicalAsync,
  getPostsByCategoryPathAsync,
  getChildCategoriesAsync,
  getChildCategoriesWithTagsAsync,
  getPostsByTagAsync,
} from './mdx';
